# Generated by Django 2.2.7 on 2019-12-09 08:04

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('gender', models.BooleanField(null=True)),
                ('level_point', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('count_top', models.IntegerField(default=0)),
                ('count_bottom', models.IntegerField(default=0)),
                ('count_shoes', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cate1',
            fields=[
                ('cate1', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cate1_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Coordi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('elem_list', models.TextField()),
                ('is_daily', models.BooleanField()),
                ('bg_type', models.CharField(max_length=20)),
                ('wear_at', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate1_name', models.CharField(max_length=20)),
                ('cate2_name', models.CharField(max_length=20)),
                ('part', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=256)),
                ('color', models.CharField(max_length=40, null=True)),
                ('solid', models.BooleanField(null=True)),
                ('pattern', models.CharField(max_length=15, null=True)),
                ('season', models.CharField(max_length=30, null=True)),
                ('descript', models.CharField(max_length=100, null=True)),
                ('worn', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=30, null=True)),
                ('texture', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cate2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cate2', models.CharField(max_length=20)),
                ('cate2_name', models.CharField(max_length=20)),
                ('worn', models.IntegerField(default=0)),
                ('cate1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.Cate1')),
            ],
        ),
        migrations.AddField(
            model_name='cate1',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hipdrobe.Part'),
        ),
    ]
